### ISSUE TITLE
Bond slip direction issue

### ISSUE THREAD

**Issue by kengwit** [NumSoftware/Amaru.jl#41]
Hi,

I was reading your paper: https://www.sciencedirect.com/science/article/abs/pii/S0168874X21001189

and was interested to try out your Amaru code on bond slip. I did a small test:
 - a unit cube block 
 - a unit length truss element in the vertical (Z) direction; for simplicity, I used cellshape=LIN2
 - interface element between the cube and truss
 - all properties are elastic
  
I pull the truss at the top uz = +0.04, but the bottom node of the truss pushes out (uz = -0.01682072494456447). Shouldn't the bottom node move in the positive Z direction? Is there a bug?

The example julia file (extension .jl renamed to .txt) is attached: [semi-embedded_Z.txt](https://github.com/user-attachments/files/18050305/semi-embedded_Z.txt)

Thanks,
Kengwit

**Comment by RaulDurand** [comment]
Hi Kengwit,

Your test seems to be an excellent benchmark for evaluating bond-slip behavior. I tried your script with different discretizations and interface properties, and here are my observations:

- For discretizations other than the 1x1x1 block, the script works as expected.  
- For LIN3 quadratic bar elements, it seems to work fine even with the 1x1x1 discretization.  
- For  k_s  values reasonably smaller than  k_n , the results are also consistent.  
- However, with a 1x1x1 discretization and  k_s = k_n = 5e10, I observed unexpected behavior.

I reviewed the code and didn’t find any issues with the implementation of LIN2 and LIN3 for the bar elements. I believe the unexpected displacement values may stem from numerical errors in solving the linear system due to the use of such high penalty parameter values for  k_s  and k_n .

You might want to consider using  k_s  values that are more aligned with the bar-concrete stiffness from pull-out tests (e.g., based on the CEB model). A reasonable suggestion could be:

- Set  k_s  to approximately 50 GPa/m (or a similar value based on your material model).
- Choose  k_n  to be around  k_s x 10^3 .

Make sure the units you are using are consistent. For example, if you define force in kN and displacement in m, then stress corresponds to kPa (as does Young’s modulus), and both  k_s and  k_n should be expressed in kPa/m.

Hope it helps.

**Comment by kengwit** [comment]
Hi, 

Thanks for your response. In the input file I sent you, I was using units of Newton, m, Pa. Therefore:

- the unit cube is 1 m x 1 m x 1m
- Concrete E (in MPa) is based on 4700 * sqrt (f'c) where f'c = 35 MPa; I then multiply this by 1e6 to convert this to Pa
- Steel is 200 x 10^9 Pa
- ks is 50 x 10^9 Pa/m, which is what you suggested (I actually took this value from one of your examples in your paper)
